services:
  sbertorgibot:
    image: ghcr.io/nousees/sbertorgibot:v0.0.3
    restart: unless-stopped
    environment:
      - TORGI_BOT_TOKEN=${TORGI_BOT_TELEGRAM_TOKEN}
      - TORGI_BOT_USERNAME=${TORGI_BOT_TELEGRAM_USERNAME}
  fsspbot:
    image: ghcr.io/danila2605/fsspbot:v0.0.9
    restart: unless-stopped
    environment:
      - FSSP_BOT_TOKEN=${FSSP_BOT_TELEGRAM_TOKEN}
      - FSSP_BOT_USERNAME=${FSSP_BOT_TELEGRAM_USERNAME}